[pyprland]
plugins = ["scratchpads"]

[scratchpads.messenger]
command = "element-desktop"
animation = "fromTop"
size = "70% 80%"
excludes = "*"
class = "Element"
pinned = false

[scratchpads.telegram]
command = "Telegram"
animation = "fromTop"
size = "70% 80%"
excludes = "*"
pinned = false

[scratchpads.terminal]
command = "foot --title terminal-popup"
class = "terminal-popup"
animation = "fromTop"
size = "70% 80%"
excludes = "*"
pinned = false

[scratchpads.music-player]
command = "foot --title music-player rmpc"
animation = "fromTop"
size = "70% 80%"
excludes = "*"
pinned = false
