[unstable]
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option
profile-rustflags = true

[registries.zubr]
index = "ssh://git@git.tt-int.net/shared/crates/index.git"

[registries.legacy]
index = "ssh://git.tt-int.net/shared/crates/index.git"

[registries.internal]
index = "ssh://git@git.tt-int.net/phoenex/shared/crate-index.git"
